// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const insertJob = `-- name: InsertJob :one
INSERT INTO jobs(id, payload, status, retry_count, max_retries, idempotency_key, scheduled_at,  created_at, updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, payload, status, retry_count, max_retries, idempotency_key, scheduled_at, created_at, updated_at
`

type InsertJobParams struct {
	ID             uuid.UUID
	Payload        json.RawMessage
	Status         sql.NullString
	RetryCount     int32
	MaxRetries     int32
	IdempotencyKey string
	ScheduledAt    sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, insertJob,
		arg.ID,
		arg.Payload,
		arg.Status,
		arg.RetryCount,
		arg.MaxRetries,
		arg.IdempotencyKey,
		arg.ScheduledAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.IdempotencyKey,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
