// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type DeadLetterJob struct {
	ID             uuid.UUID
	JobID          uuid.UUID
	Payload        json.RawMessage
	Status         string
	Type           string
	RetryCount     int32
	MaxRetries     int32
	IdempotencyKey sql.NullString
	ScheduledAt    sql.NullTime
	CreatedAt      time.Time
	FailureReason  sql.NullString
	OriginalError  sql.NullString
}

type Job struct {
	ID             uuid.UUID
	Payload        json.RawMessage
	Status         sql.NullString
	Type           string
	RetryCount     int32
	MaxRetries     int32
	IdempotencyKey string
	ScheduledAt    sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
	NextRunAt      sql.NullTime
	Priority      int32
}

type Webhook struct {
	ID        uuid.UUID
	URL       string
	JobType   string
	Event     string
	Secret    sql.NullString
	CreatedAt time.Time
}
