// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Job struct {
	ID             uuid.UUID
	Payload        json.RawMessage
	Status         sql.NullString
	Type           string
	RetryCount     int32
	MaxRetries     int32
	IdempotencyKey string
	ScheduledAt    sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
	NextRunAt      sql.NullTime
}
